# SPDX-FileCopyrightText: 2022 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0

accepted = ["Apache-2.0", "MIT", "0BSD", "BSD-3-Clause"]

ignore-build-dependencies = false
ignore-dev-dependencies = false
ignore-transitive-dependencies = false
filter-noassertion = true
